image: node:14

stages:
  - test
  - build

variables:
  POSTGRES_DB: todo_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password

services:
  - name: postgres:13

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm install
    - npm run build
